apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-blue
  labels:
    app: messaging
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
      version: blue
  template:
    metadata:
      labels:
        app: messaging
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: dyphineanyanga/messaging-app:2.0
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
