apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
  labels:
    app: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: django-messaging-app
        image: your-dockerhub-username/django-messaging-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
