apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
      version: green
  template:
    metadata:
      labels:
        app: messaging
        version: green
    spec:
      containers:
      - name: messaging-app
        image: your-dockerhub-username/messaging-app:green  # replace with your real image
        ports:
        - containerPort: 8000
