pipeline {
    agent any

    tools {
        python 'Python 3'
    }

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/DyphineAnyanga/alx-backend-python.git'
                sh 'git branch'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh 'python3 -m venv ${VENV_DIR}'
                sh './${VENV_DIR}/bin/pip3 install --upgrade pip'
                sh './${VENV_DIR}/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './${VENV_DIR}/bin/pytest messaging_app/tests/ --junitxml=test-results.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'test-results.xml'
            }
        }
    }
}
