pipeline {
    agent any

    tools {
        python 'Python 3' // Must match your ShiningPanda setup
    }

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
    }

    stages {
        stage('Clone Repo') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/DyphineAnyanga/alx-backend-python.git'
            }
        }

        stage('Setup Python & Install Deps') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/pytest messaging_app/tests/ --junitxml=test-results.xml'
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'test-results.xml'
            }
        }
    }
}
