# Generated by Django 4.2.11 on 2025-06-18 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_alter_message_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='content_before_edit',
            new_name='old_content',
        ),
        migrations.RemoveField(
            model_name='messagehistory',
            name='original_message',
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='messaging.message'),
            preserve_default=False,
        ),
    ]
