apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
    version: blue   # Initially routes to blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
